name: 📚 Documentation Improvement
description: Suggest an improvement to the UiBrium documentation
labels: ["documentation"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: Link to the page or section that needs improvement.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What should be changed or added?
    validations:
      required: true
